<header>
	ADMIN
	<div class="logo">
		<a href="index.php">
			<img class="logo_img" src="./style/black-cat.svg" alt="">
			<h1>Chat Project</h1>
		</a>
	</div>
	<nav class="menu_users">
		<a href="index.php?page=users">Profil</a>
		<a href="index.php?page=logout">Logout</a>
	</nav>
	<div class="user">
		<p>Bonjour <strong><?=htmlentities($_SESSION['login'])?></strong>, vous êtes maintenant connecté(e) en tant que <strong>Admin</strong> !</p>
	</div>
</header>