<div class="box_chat">
		<div class="users">
		
		</div>
		<div class="message">
			<div class="users_in">
				<p><strong>Maud, Laetitia et Jb</strong> : sont entrain de discuter</p>
			</div>
			<div class="affichage_message">
				<?php require('apps/message.php') ?>
			</div>
			<div class="box_writeMessage">
				<form method="post" action="">
					<label for=""></label>
					<input placeholder="Ecrivez votre message" type="text" name="content" id="" autofocus/>
					<input class="bouton_envoyer" type="submit" value="envoyer">
				</form>
			</div>
		</div>
</div>
