<div class="box_chat">
		<div class="users">
		
		</div>
		<div class="message">
			<div class="users_in">
				<p><strong>Maud, Laetitia et Jb</strong> : sont entrain de discuter</p>
			</div>
			<div class="affichage_message">
				<?php require('message.php') ?>
			</div>
			<div class="box_writeMessage">
				<form action="">
					<label for=""></label>
					<textarea placeholder="Ecrivez votre message" name="" id="" cols="30" rows="10"></textarea>
					<input class="bouton_envoyer" type="submit" value="envoyer">
				</form>
			</div>
		</div>
</div>
