<div class="container">
		<div class="box_register">
			<h1>Créer un compte</h1>
			<form method="post">
				<input type="hidden" name="action" value="register">
				<div class="box_infosRegister">
						<label>Votre identifiant:</label>
						<input type="text" name="login" />
						<label>Votre e-mail:</label>
						<input type="text" name="email">	
						<label>Votre date de naissance:</label>
						<input type="date" name="birthdate">
						<label>Taper votre mot de passe:</label>
						<input type="password" name="password1" />
						<label>Retapez votre mot de passe:</label>
						<input type="password" name="password2" />
				</div>
				<div class="box_avatar">
					<label>Avatar</label>
					<input type="url" name="avatar" placeholder="lien url">
				</div>
					<input class="bouton_login" type="submit" value="Valider"/>
			</form>
		</div>
</div>

