<div class="container">
	<h1>Formulaire d'inscription</h1>
	<form action="" method="post">
	<input type="hidden" name="action" value="register">
		<label for="login">Login</label>
		<input name="login" type="text">
		<label for="date_birth">Date de naissance</label>
		<input name="date_birth" type="date">
		<label for="mail">Email</label>
		<input name="mail"type="text">
		<label for="password1">Mot de passe</label>
		<input name="password1" type="password">
		<label for="password2">Retype Password</label>
		<input type="password" name="password2">
		<input type="submit" value="valider">

	</form>
</div>