<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Chat Project</title>
	<link rel="stylesheet" href="style/style.css">
	<link href="https://fonts.googleapis.com/css?family=Oxygen:400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Caveat+Brush" rel="stylesheet">


</head>
<body>
	<div class="container">
		<?php require ('apps/header.php'); ?>
		<?php require('apps/container.php'); ?>
		<?php require('apps/footer.php'); ?>

</div>
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>

</body>
</html>